# Generated by Django 4.0.6 on 2022-07-28 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualAccount',
            fields=[
                ('account_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('account_type', models.CharField(max_length=20)),
                ('bank', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=2)),
                ('currency', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('recipient', models.CharField(max_length=200)),
                ('confirmed', models.BooleanField()),
                ('timestamp', models.DateTimeField()),
                ('receipt', models.CharField(max_length=100)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rapyd.virtualaccount')),
            ],
        ),
    ]
